parameters:
    flask.app.name: shirka
    flask.app.port: 8080

services:
    shirka.flask:
        class: flask.Flask
        arguments: ['%flask.app.name%']
        calls:
            - [add_url_rule, ['/process'],            {view_func: '@shirka.flask.view.shirka_proc_list'}]
            - [add_url_rule, ['/process/<id>'],       {view_func: '@shirka.flask.view.shirka_proc_view'}]
            - [add_url_rule, ['/process/<id>/<fd>'],  {view_func: '@shirka.flask.view.shirka_proc_read_view'}]

    shirka.flask.view.shirka_proc_list:
        class: shirka.control.proc.ProcListView.as_view
        arguments: 
            - shirka_proc_list
            - "%shirka.data.dir%"

    shirka.flask.view.shirka_proc_view:
        class: shirka.control.proc.ProcView.as_view
        arguments: 
            - shirka_proc_view
            - "%shirka.data.dir%"

    shirka.flask.view.shirka_proc_read_view:
        class: shirka.control.proc.ProcReadView.as_view
        arguments: 
            - shirka_proc_read_view
            - "%shirka.data.dir%"

    shirka.twisted.web.resource:
        class: twisted.web.resource.Resource
        calls:
            - [putChild, ['public', '@shirka.twisted.web.resource.static']]
            - [putChild, ['api', '@shirka.twisted.web.resource.wsgi']]

    shirka.twisted.web.resource.static:
        class: twisted.web.static.File
        arguments: 
            - '%shirka.web.public.dir%'

    shirka.twisted.web.resource.wsgi:
        class: twisted.web.wsgi.WSGIResource
        arguments: 
            - '@shirka.twisted.reactor'
            - '@shirka.twisted.reactor.thread_pool'
            - '@shirka.flask'

    shirka.twisted.web.site:
        class: twisted.web.server.Site
        arguments: 
            - '@shirka.twisted.web.resource'

    shirka.twisted.reactor:
        class: twisted.internet.reactor
        # calls:
            # - [listenTCP, ['%flask.app.port%', '@shirka.twisted.web.site']]

    shirka.twisted.reactor.thread_pool:
        class: twisted.internet.reactor.getThreadPool